[package]
name = "impala"
description = "IMPure functionAl LAnguage"
license-file = "LICENSE.txt"
keywords = ["language"]
categories = ["compilers", "virtual machines"]
version = "0.0.1"
edition = "2021"
authors = ["Nobuharu Shimazu <nobu.bichanna@gmail.com>"]
repository = "https://github.com/bichanna/impala"

[dependencies]
crossbeam-channel = "0.5"
byteorder = "1"
