[package]
name = "feo"
description = "A mildly functional, minimal programming language compiled to FVM bytecode"
license-file = "LICENSE.txt"
keywords = ["language"]
categories = ["compilers"]
version = "0.0.1"
edition = "2021"
authors = ["Nobuharu Shimazu <nobu.bichanna@gmail.com>"]
repository = "https://github.com/bichanna/feo"

[dependencies]
crossbeam-channel = "0.5"
byteorder = "1"
